package dark_matter_scanner;

import java.sql.*;
import java.sql.Types;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

// ========================================
// BLOCK 1 — DATABASE SERVICE
// ========================================
public class DatabaseService {

    // ========================================
    // BLOCK 2 — DB CONFIG
    // ========================================
    private static final String DB_URL = "jdbc:postgresql://localhost:5432/dark_matter_scanner";
    private static final String DB_USER = "postgres";
    private static final String DB_PASS = "doonoot";

    // ========================================
    // BLOCK 3 — GET CONNECTION
    // ========================================
    public Connection getConnection() throws Exception {
        return DriverManager.getConnection(DB_URL, DB_USER, DB_PASS);
    }

    // ========================================
    // BLOCK 3B — ENSURE OUI METADATA TABLE
    // ========================================
    private void ensureOuiMetadataTable(Connection conn) throws Exception {
        String ddl = """
            CREATE TABLE IF NOT EXISTS mac_oui_metadata (
                oui                     VARCHAR(8) PRIMARY KEY,
                critical_infrastructure BOOLEAN      NOT NULL DEFAULT FALSE,
                equipment_type          TEXT,
                role_hint               TEXT,
                notes                   TEXT,
                updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW()
            )
        """;

        try (PreparedStatement stmt = conn.prepareStatement(ddl)) {
            stmt.execute();
        }
    }

    public void ensureOuiMetadataSchema() throws Exception {
        try (Connection conn = getConnection()) {
            ensureOuiMetadataTable(conn);
        }
    }

    // ========================================
    // BLOCK 3C — ENSURE SNMP WALK TABLE
    // ========================================
    public void ensureSnmpWalkSchema() throws Exception {
        String ddl = """
            CREATE TABLE IF NOT EXISTS snmp_walk_runs (
                id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                scan_id       INTEGER REFERENCES scan_runs(id) ON DELETE CASCADE,
                observed_ip   INET        NOT NULL,
                auth_mode     TEXT        NOT NULL DEFAULT 'v2c',
                oid_root      TEXT        NOT NULL DEFAULT '1.3.6.1.2.1',
                status        TEXT        NOT NULL DEFAULT 'running',
                raw_output    TEXT,
                error_text    TEXT,
                started_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                completed_at  TIMESTAMPTZ
            )
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(ddl)
        ) {
            stmt.execute();
        }
    }

    // ========================================
    // BLOCK 4 — CREATE SCAN RUN
    // ========================================
    public int createScanRun(String subnet, String iface, String host, boolean sshUsed) throws Exception {

        String sql = """
            INSERT INTO scan_runs (subnet, interface, target_host, ssh_used, status)
            VALUES (?, ?, ?, ?, 'running')
            RETURNING id
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            stmt.setString(1, subnet);
            stmt.setString(2, iface);
            stmt.setString(3, host);
            stmt.setBoolean(4, sshUsed);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("id");
                }
            }
        }

        throw new RuntimeException("Failed to create scan_runs record.");
    }

    // ========================================
    // BLOCK 5 — COMPLETE SCAN
    // ========================================
    public void completeScan(int scanId, String rawOutput) throws Exception {

        String sql = """
            UPDATE scan_runs
            SET status = 'complete',
                raw_output = ?
            WHERE id = ?
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            stmt.setString(1, rawOutput);
            stmt.setInt(2, scanId);
            stmt.executeUpdate();
        }
    }

    // ========================================
    // BLOCK 6 — UPSERT ARP BINDING
    // ========================================
    public void upsertArpBinding(int scanId, String ip, String mac, String source, Double rttMs, String responseType) throws Exception {

        String sql = """
            INSERT INTO arp_bindings (scan_id, observed_ip, mac_address, source, rtt_ms, response_type)
            VALUES (?, ?::inet, ?, ?, ?, ?)
            ON CONFLICT (scan_id, observed_ip, mac_address, source)
            DO UPDATE SET
                last_seen = now(),
                seen_count = arp_bindings.seen_count + 1,
                rtt_ms = EXCLUDED.rtt_ms,
                response_type = EXCLUDED.response_type
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            stmt.setInt(1, scanId);
            stmt.setString(2, ip);
            if (mac != null && !mac.isBlank()) {
                stmt.setString(3, mac.trim().toUpperCase());
            } else {
                stmt.setNull(3, Types.VARCHAR);
            }
            stmt.setString(4, source);

            if (rttMs != null) {
                stmt.setDouble(5, rttMs);
            } else {
                stmt.setNull(5, Types.DOUBLE);
            }

            stmt.setString(6, responseType);
            stmt.executeUpdate();
        }
    }

    // ========================================
    // BLOCK 7 — GET INTERFACE FOR SCAN
    // ========================================
    public String getInterfaceForScan(int scanId) throws Exception {

        String sql = """
            SELECT interface
            FROM scan_runs
            WHERE id = ?
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            stmt.setInt(1, scanId);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getString("interface");
                }
            }
        }

        throw new RuntimeException("Scan not found: " + scanId);
    }

    // ========================================
    // BLOCK 8 — CREATE TCPDUMP CAPTURE
    // ========================================
    public long createTcpdumpCapture(
            int scanId,
            String captureMethod,
            String captureHost,
            String interfaceName,
            String captureFilter,
            int durationSeconds
    ) throws Exception {

        String sql = """
            INSERT INTO tcpdump_captures
                (scan_id, capture_method, capture_host, interface_name, capture_filter, duration_seconds, status)
            VALUES
                (?, ?, ?, ?, ?, ?, 'running')
            RETURNING id
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            stmt.setInt(1, scanId);
            stmt.setString(2, captureMethod);
            stmt.setString(3, captureHost);
            stmt.setString(4, interfaceName);
            stmt.setString(5, captureFilter);
            stmt.setInt(6, durationSeconds);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getLong("id");
                }
            }
        }

        throw new RuntimeException("Failed to create tcpdump_captures record.");
    }

    // ========================================
    // BLOCK 9 — COMPLETE TCPDUMP CAPTURE
    // ========================================
    public void completeTcpdumpCapture(long captureId, String rawOutput) throws Exception {

        String sql = """
            UPDATE tcpdump_captures
            SET status = 'complete',
                raw_output = ?,
                ended_at = now()
            WHERE id = ?
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            stmt.setString(1, rawOutput);
            stmt.setLong(2, captureId);
            stmt.executeUpdate();
        }
    }

    // ========================================
    // BLOCK 10 — FAIL TCPDUMP CAPTURE
    // ========================================
    public void failTcpdumpCapture(long captureId, String errorText) throws Exception {

        String sql = """
            UPDATE tcpdump_captures
            SET status = 'failed',
                raw_output = ?,
                ended_at = now()
            WHERE id = ?
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            stmt.setString(1, errorText);
            stmt.setLong(2, captureId);
            stmt.executeUpdate();
        }
    }

    // ========================================
    // BLOCK 11 — INSERT MAC OBSERVATION
    // ========================================
    public void insertMacObservation(
            int scanId,
            long captureId,
            String srcMac,
            String srcIp,
            String dstMac,
            String dstIp,
            String protocol,
            String note,
            String rawLine
    ) throws Exception {

        String sql = """
            INSERT INTO mac_observations
                (scan_id, capture_id, src_mac, src_ip, dst_mac, dst_ip, protocol, note, raw_line)
            VALUES
                (?, ?, ?, ?::inet, ?, ?::inet, ?, ?, ?)
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            stmt.setInt(1, scanId);
            stmt.setLong(2, captureId);

            if (srcMac != null && !srcMac.isBlank()) {
                stmt.setString(3, srcMac);
            } else {
                stmt.setNull(3, Types.VARCHAR);
            }

            if (srcIp != null && !srcIp.isBlank()) {
                stmt.setString(4, srcIp);
            } else {
                stmt.setNull(4, Types.VARCHAR);
            }

            if (dstMac != null && !dstMac.isBlank()) {
                stmt.setString(5, dstMac);
            } else {
                stmt.setNull(5, Types.VARCHAR);
            }

            if (dstIp != null && !dstIp.isBlank()) {
                stmt.setString(6, dstIp);
            } else {
                stmt.setNull(6, Types.VARCHAR);
            }

            stmt.setString(7, protocol != null ? protocol : "ARP");

            if (note != null && !note.isBlank()) {
                stmt.setString(8, note);
            } else {
                stmt.setNull(8, Types.VARCHAR);
            }

            stmt.setString(9, rawLine);
            stmt.executeUpdate();
        }
    }

    // ========================================
    // BLOCK 11B — BATCH INSERT MAC OBSERVATIONS
    // ========================================
    public int insertMacObservationsBatch(List<TcpdumpParserService.MacObservationRecord> rows) throws Exception {

        if (rows == null || rows.isEmpty()) {
            return 0;
        }

        String sql = """
            INSERT INTO mac_observations
                (scan_id, capture_id, src_mac, src_ip, dst_mac, dst_ip, protocol, note, raw_line)
            VALUES
                (?, ?, ?, ?::inet, ?, ?::inet, ?, ?, ?)
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            conn.setAutoCommit(false);

            try {
                int batchCount = 0;

                for (TcpdumpParserService.MacObservationRecord row : rows) {
                    stmt.setInt(1, row.getScanId());
                    stmt.setLong(2, row.getCaptureId());

                    if (row.getSrcMac() != null && !row.getSrcMac().isBlank()) {
                        stmt.setString(3, row.getSrcMac());
                    } else {
                        stmt.setNull(3, Types.VARCHAR);
                    }

                    if (row.getSrcIp() != null && !row.getSrcIp().isBlank()) {
                        stmt.setString(4, row.getSrcIp());
                    } else {
                        stmt.setNull(4, Types.VARCHAR);
                    }

                    if (row.getDstMac() != null && !row.getDstMac().isBlank()) {
                        stmt.setString(5, row.getDstMac());
                    } else {
                        stmt.setNull(5, Types.VARCHAR);
                    }

                    if (row.getDstIp() != null && !row.getDstIp().isBlank()) {
                        stmt.setString(6, row.getDstIp());
                    } else {
                        stmt.setNull(6, Types.VARCHAR);
                    }

                    stmt.setString(7, row.getProtocol() != null ? row.getProtocol() : "ARP");

                    if (row.getNote() != null && !row.getNote().isBlank()) {
                        stmt.setString(8, row.getNote());
                    } else {
                        stmt.setNull(8, Types.VARCHAR);
                    }

                    stmt.setString(9, row.getRawLine());
                    stmt.addBatch();
                    batchCount++;

                    if (batchCount % 1000 == 0) {
                        stmt.executeBatch();
                    }
                }

                stmt.executeBatch();
                conn.commit();
                return rows.size();

            } catch (Exception e) {
                conn.rollback();
                throw e;
            } finally {
                conn.setAutoCommit(true);
            }
        }
    }

    // ========================================
    // BLOCK 11C — UPSERT PASSIVE ARP BINDINGS FROM OBSERVATIONS
    // ========================================
    public int upsertPassiveArpBindingsFromObservations(int scanId, List<TcpdumpParserService.MacObservationRecord> rows) throws Exception {

        if (rows == null || rows.isEmpty()) {
            return 0;
        }

        String sql = """
            INSERT INTO arp_bindings (scan_id, observed_ip, mac_address, source, rtt_ms, response_type)
            VALUES (?, ?::inet, ?, 'passive_tcpdump', NULL, 'passive_tcpdump')
            ON CONFLICT (scan_id, observed_ip, mac_address, source)
            DO UPDATE SET
                last_seen = now(),
                seen_count = arp_bindings.seen_count + 1
        """;

        String scanSubnet = getScanSubnet(scanId);

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            conn.setAutoCommit(false);

            try {
                int promotedCount = 0;
                Set<String> seenPairs = new HashSet<>();

                for (TcpdumpParserService.MacObservationRecord row : rows) {
                    if (!"ARP".equalsIgnoreCase(row.getProtocol())) {
                        continue;
                    }
                    promotedCount += addPassiveCandidate(stmt, seenPairs, scanId, scanSubnet, row.getSrcIp(), row.getSrcMac());
                    promotedCount += addPassiveCandidate(stmt, seenPairs, scanId, scanSubnet, row.getDstIp(), row.getDstMac());
                }

                stmt.executeBatch();
                conn.commit();
                return promotedCount;

            } catch (Exception e) {
                conn.rollback();
                throw e;
            } finally {
                conn.setAutoCommit(true);
            }
        }
    }

    // ========================================
    // BLOCK 11D — UPSERT PASSIVE IPV4 UNICAST BINDINGS FROM OBSERVATIONS
    // ========================================
    public int upsertPassiveIpv4BindingsFromObservations(int scanId, List<TcpdumpParserService.MacObservationRecord> rows) throws Exception {

        if (rows == null || rows.isEmpty()) {
            return 0;
        }

        String sql = """
            INSERT INTO arp_bindings (scan_id, observed_ip, mac_address, source, rtt_ms, response_type)
            VALUES (?, ?::inet, ?, 'passive_ipv4', NULL, 'passive_ipv4')
            ON CONFLICT (scan_id, observed_ip, mac_address, source)
            DO UPDATE SET
                last_seen = now(),
                seen_count = arp_bindings.seen_count + 1
        """;

        String scanSubnet = getScanSubnet(scanId);

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            conn.setAutoCommit(false);

            try {
                int promotedCount = 0;
                Set<String> seenPairs = new HashSet<>();

                for (TcpdumpParserService.MacObservationRecord row : rows) {
                    if (!"IPv4".equalsIgnoreCase(row.getProtocol())) {
                        continue;
                    }
                    if (row.getNote() != null && !"unicast".equalsIgnoreCase(row.getNote())) {
                        continue;
                    }
                    promotedCount += addPassiveCandidate(
                            stmt,
                            seenPairs,
                            scanId,
                            scanSubnet,
                            row.getSrcIp(),
                            row.getSrcMac()
                    );
                }

                stmt.executeBatch();
                conn.commit();
                return promotedCount;

            } catch (Exception e) {
                conn.rollback();
                throw e;
            } finally {
                conn.setAutoCommit(true);
            }
        }
    }

    private int addPassiveCandidate(
            PreparedStatement stmt,
            Set<String> seenPairs,
            int scanId,
            String scanSubnet,
            String ip,
            String mac
    ) throws Exception {

        if (!isUsableIpv4(ip) || !isUsableUnicastMac(mac)) {
            return 0;
        }

        String normalizedIp = ip.trim();
        if (!isIpInSubnet(normalizedIp, scanSubnet)) {
            return 0;
        }
        String normalizedMac = mac.trim().toUpperCase();
        String key = normalizedIp + "|" + normalizedMac;

        if (!seenPairs.add(key)) {
            return 0;
        }

        stmt.setInt(1, scanId);
        stmt.setString(2, normalizedIp);
        stmt.setString(3, normalizedMac);
        stmt.addBatch();
        return 1;
    }

    private String getScanSubnet(int scanId) throws Exception {
        String sql = """
            SELECT subnet
            FROM scan_runs
            WHERE id = ?
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            stmt.setInt(1, scanId);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getString("subnet");
                }
            }
        }

        return null;
    }

    private boolean isUsableIpv4(String ip) {
        if (ip == null) {
            return false;
        }
        String value = ip.trim();
        if (value.isEmpty() || "0.0.0.0".equals(value)) {
            return false;
        }

        String[] parts = value.split("\\.");
        if (parts.length != 4) {
            return false;
        }

        for (String part : parts) {
            if (part.isEmpty() || part.length() > 3) {
                return false;
            }
            try {
                int octet = Integer.parseInt(part);
                if (octet < 0 || octet > 255) {
                    return false;
                }
            } catch (NumberFormatException e) {
                return false;
            }
        }

        return true;
    }

    private boolean isUsableUnicastMac(String mac) {
        if (mac == null) {
            return false;
        }
        String value = mac.trim().toUpperCase();

        if (!value.matches("^[0-9A-F]{2}(:[0-9A-F]{2}){5}$")) {
            return false;
        }
        if ("00:00:00:00:00:00".equals(value) || "FF:FF:FF:FF:FF:FF".equals(value)) {
            return false;
        }

        try {
            int firstOctet = Integer.parseInt(value.substring(0, 2), 16);
            return (firstOctet & 1) == 0;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private boolean isIpInSubnet(String ip, String subnetCidr) {
        if (!isUsableIpv4(ip) || subnetCidr == null || subnetCidr.isBlank()) {
            return false;
        }

        String cidr = subnetCidr.trim();
        int slash = cidr.indexOf('/');
        if (slash <= 0 || slash >= cidr.length() - 1) {
            return false;
        }

        String networkIp = cidr.substring(0, slash).trim();
        String prefixText = cidr.substring(slash + 1).trim();
        if (!isUsableIpv4(networkIp)) {
            return false;
        }

        int prefix;
        try {
            prefix = Integer.parseInt(prefixText);
        } catch (NumberFormatException e) {
            return false;
        }
        if (prefix < 0 || prefix > 32) {
            return false;
        }

        long ipValue = ipv4ToLong(ip);
        long netValue = ipv4ToLong(networkIp);
        if (ipValue < 0 || netValue < 0) {
            return false;
        }

        long mask = prefix == 0 ? 0L : (0xFFFFFFFFL << (32 - prefix)) & 0xFFFFFFFFL;
        return (ipValue & mask) == (netValue & mask);
    }

    private long ipv4ToLong(String ip) {
        if (!isUsableIpv4(ip)) {
            return -1L;
        }

        String[] parts = ip.split("\\.");
        long value = 0L;
        for (String part : parts) {
            int octet;
            try {
                octet = Integer.parseInt(part);
            } catch (NumberFormatException e) {
                return -1L;
            }
            value = (value << 8) | (octet & 0xFFL);
        }
        return value;
    }

    // ========================================
    // BLOCK 12 — DELETE TCPDUMP CAPTURE
    // ========================================
    public void deleteTcpdumpCapture(int scanId, long captureId) throws Exception {

        String deleteObservationsSql = """
            DELETE FROM mac_observations
            WHERE scan_id = ?
              AND capture_id = ?
        """;

        String deleteCaptureSql = """
            DELETE FROM tcpdump_captures
            WHERE scan_id = ?
              AND id = ?
        """;

        try (Connection conn = getConnection()) {
            conn.setAutoCommit(false);

            try (
                    PreparedStatement deleteObservationsStmt = conn.prepareStatement(deleteObservationsSql);
                    PreparedStatement deleteCaptureStmt = conn.prepareStatement(deleteCaptureSql)
            ) {
                deleteObservationsStmt.setInt(1, scanId);
                deleteObservationsStmt.setLong(2, captureId);
                deleteObservationsStmt.executeUpdate();

                deleteCaptureStmt.setInt(1, scanId);
                deleteCaptureStmt.setLong(2, captureId);
                int deletedCaptureRows = deleteCaptureStmt.executeUpdate();

                if (deletedCaptureRows == 0) {
                    throw new RuntimeException("Capture not found for scan " + scanId + ": " + captureId);
                }

                conn.commit();

            } catch (Exception e) {
                conn.rollback();
                throw e;
            } finally {
                conn.setAutoCommit(true);
            }
        }
    }

    // ========================================
    // BLOCK 13 — DELETE SCAN COMPLETELY
    // ========================================
    public void deleteScanCompletely(int scanId) throws Exception {

        try (Connection conn = getConnection()) {

            conn.setAutoCommit(false);

            try {
                deleteChildren(conn, "node_classifications", scanId);
                deleteChildren(conn, "service_observations", scanId);
                deleteChildren(conn, "mac_observations", scanId);
                deleteChildren(conn, "tcpdump_captures", scanId);
                deleteChildren(conn, "arp_bindings", scanId);
                deleteChildren(conn, "network_edges", scanId);
                deleteChildren(conn, "mac_relationships", scanId);
                deleteChildren(conn, "mac_peer_stats", scanId);
                deleteChildren(conn, "inferred_devices", scanId);
                deleteChildren(conn, "nodes", scanId);

                try (PreparedStatement stmt = conn.prepareStatement(
                        "DELETE FROM scan_runs WHERE id = ?"
                )) {
                    stmt.setInt(1, scanId);
                    stmt.executeUpdate();
                }

                conn.commit();

            } catch (Exception e) {
                conn.rollback();
                throw e;
            }
        }
    }

    // ========================================
    // BLOCK 14 — DELETE CHILD HELPER
    // ========================================
    private void deleteChildren(Connection conn, String tableName, int scanId) throws Exception {

        String sql = "DELETE FROM " + tableName + " WHERE scan_id = ?";

        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, scanId);
            stmt.executeUpdate();
        }
    }

    // ========================================
    // BLOCK 15 — LOAD SCAN NODE ADDRESSES
    // ========================================
    public List<NodeAddress> loadScanNodeAddresses(int scanId) throws Exception {

        String sql = """
            WITH ranked AS (
                SELECT
                    host(observed_ip) AS observed_ip,
                    mac_address,
                    COALESCE(v.vendor_clean, v.vendor, 'Unknown') AS vendor,
                    ROW_NUMBER() OVER (
                        PARTITION BY observed_ip
                        ORDER BY
                            (CASE WHEN rtt_ms IS NOT NULL THEN 1 ELSE 0 END) DESC,
                            (CASE WHEN mac_address IS NOT NULL THEN 1 ELSE 0 END) DESC,
                            seen_count DESC,
                            last_seen DESC NULLS LAST
                    ) AS rn
                FROM arp_bindings
                LEFT JOIN mac_oui_lookup v
                  ON LEFT(REGEXP_REPLACE(UPPER(arp_bindings.mac_address), '[^0-9A-F]', '', 'g'), 6)
                   = LEFT(REGEXP_REPLACE(UPPER(v.oui),                   '[^0-9A-F]', '', 'g'), 6)
                WHERE scan_id = ?
                  AND observed_ip IS NOT NULL
            )
            SELECT observed_ip, mac_address, vendor
            FROM ranked
            WHERE rn = 1
            ORDER BY observed_ip
        """;

        List<NodeAddress> rows = new ArrayList<>();

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            stmt.setInt(1, scanId);

            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    rows.add(new NodeAddress(
                            rs.getString("observed_ip"),
                            rs.getString("mac_address"),
                            rs.getString("vendor")
                    ));
                }
            }
        }

        return rows;
    }

    // ========================================
    // BLOCK 16 — CLEAR SERVICE OBSERVATIONS
    // ========================================
    public void clearServiceObservationsForScan(int scanId) throws Exception {
        String sql = "DELETE FROM service_observations WHERE scan_id = ?";

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            stmt.setInt(1, scanId);
            stmt.executeUpdate();
        }
    }

    // ========================================
    // BLOCK 17 — UPSERT SERVICE OBSERVATIONS BATCH
    // ========================================
    public int upsertServiceObservationsBatch(List<ServiceObservationRecord> rows) throws Exception {

        if (rows == null || rows.isEmpty()) {
            return 0;
        }

        String sql = """
            INSERT INTO service_observations
                (scan_id, observed_ip, mac_address, transport, port, state, service_name, product, version, extra_info, source)
            VALUES
                (?, ?::inet, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT (scan_id, observed_ip, mac_address, transport, port, source)
            DO UPDATE SET
                state = EXCLUDED.state,
                service_name = EXCLUDED.service_name,
                product = EXCLUDED.product,
                version = EXCLUDED.version,
                extra_info = EXCLUDED.extra_info,
                observed_at = NOW()
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            conn.setAutoCommit(false);

            try {
                int batchCount = 0;

                for (ServiceObservationRecord row : rows) {
                    stmt.setInt(1, row.scanId);
                    stmt.setString(2, row.observedIp);

                    if (row.macAddress != null && !row.macAddress.isBlank()) {
                        stmt.setString(3, row.macAddress.trim().toUpperCase());
                    } else {
                        stmt.setNull(3, Types.VARCHAR);
                    }

                    stmt.setString(4, row.transport != null ? row.transport : "tcp");
                    stmt.setInt(5, row.port);
                    stmt.setString(6, row.state != null ? row.state : "open");
                    stmt.setString(7, row.serviceName);
                    stmt.setString(8, row.product);
                    stmt.setString(9, row.version);
                    stmt.setString(10, row.extraInfo);
                    stmt.setString(11, row.source != null ? row.source : "nmap_sV");
                    stmt.addBatch();

                    batchCount++;
                    if (batchCount % 1000 == 0) {
                        stmt.executeBatch();
                    }
                }

                stmt.executeBatch();
                conn.commit();
                return rows.size();

            } catch (Exception e) {
                conn.rollback();
                throw e;
            } finally {
                conn.setAutoCommit(true);
            }
        }
    }

    // ========================================
    // BLOCK 18 — CLEAR NODE CLASSIFICATIONS
    // ========================================
    public void clearNodeClassificationsForScan(int scanId) throws Exception {
        String sql = "DELETE FROM node_classifications WHERE scan_id = ?";

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            stmt.setInt(1, scanId);
            stmt.executeUpdate();
        }
    }

    // ========================================
    // BLOCK 19 — UPSERT NODE CLASSIFICATIONS BATCH
    // ========================================
    public int upsertNodeClassificationsBatch(List<NodeClassificationRecord> rows) throws Exception {

        if (rows == null || rows.isEmpty()) {
            return 0;
        }

        String sql = """
            INSERT INTO node_classifications
                (scan_id, observed_ip, mac_address, node_role, confidence, score, evidence_json, classifier_version, source)
            VALUES
                (?, ?::inet, ?, ?, ?, ?, ?::jsonb, ?, ?)
            ON CONFLICT (scan_id, observed_ip, mac_address, node_role, classifier_version)
            DO UPDATE SET
                confidence = EXCLUDED.confidence,
                score = EXCLUDED.score,
                evidence_json = EXCLUDED.evidence_json,
                source = EXCLUDED.source,
                classified_at = NOW()
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            conn.setAutoCommit(false);

            try {
                int batchCount = 0;

                for (NodeClassificationRecord row : rows) {
                    stmt.setInt(1, row.scanId);
                    stmt.setString(2, row.observedIp);

                    if (row.macAddress != null && !row.macAddress.isBlank()) {
                        stmt.setString(3, row.macAddress.trim().toUpperCase());
                    } else {
                        stmt.setNull(3, Types.VARCHAR);
                    }

                    stmt.setString(4, row.nodeRole);
                    stmt.setString(5, row.confidence);

                    if (row.score != null) {
                        stmt.setDouble(6, row.score);
                    } else {
                        stmt.setNull(6, Types.DOUBLE);
                    }

                    stmt.setString(7, row.evidenceJson != null ? row.evidenceJson : "{}");
                    stmt.setString(8, row.classifierVersion != null ? row.classifierVersion : "v1");
                    stmt.setString(9, row.source != null ? row.source : "rule_engine");
                    stmt.addBatch();

                    batchCount++;
                    if (batchCount % 1000 == 0) {
                        stmt.executeBatch();
                    }
                }

                stmt.executeBatch();
                conn.commit();
                return rows.size();

            } catch (Exception e) {
                conn.rollback();
                throw e;
            } finally {
                conn.setAutoCommit(true);
            }
        }
    }

    // ========================================
    // BLOCK 20 — DTO: NODE ADDRESS
    // ========================================
    public static class NodeAddress {
        public final String observedIp;
        public final String macAddress;
        public final String vendor;

        public NodeAddress(String observedIp, String macAddress, String vendor) {
            this.observedIp = observedIp;
            this.macAddress = macAddress;
            this.vendor = vendor;
        }
    }

    // ========================================
    // BLOCK 21 — DTO: SERVICE OBSERVATION
    // ========================================
    public static class ServiceObservationRecord {
        public final int scanId;
        public final String observedIp;
        public final String macAddress;
        public final String transport;
        public final int port;
        public final String state;
        public final String serviceName;
        public final String product;
        public final String version;
        public final String extraInfo;
        public final String source;

        public ServiceObservationRecord(
                int scanId,
                String observedIp,
                String macAddress,
                String transport,
                int port,
                String state,
                String serviceName,
                String product,
                String version,
                String extraInfo,
                String source
        ) {
            this.scanId = scanId;
            this.observedIp = observedIp;
            this.macAddress = macAddress;
            this.transport = transport;
            this.port = port;
            this.state = state;
            this.serviceName = serviceName;
            this.product = product;
            this.version = version;
            this.extraInfo = extraInfo;
            this.source = source;
        }
    }

    // ========================================
    // BLOCK 22 — DTO: NODE CLASSIFICATION
    // ========================================
    public static class NodeClassificationRecord {
        public final int scanId;
        public final String observedIp;
        public final String macAddress;
        public final String nodeRole;
        public final String confidence;
        public final Double score;
        public final String evidenceJson;
        public final String classifierVersion;
        public final String source;

        public NodeClassificationRecord(
                int scanId,
                String observedIp,
                String macAddress,
                String nodeRole,
                String confidence,
                Double score,
                String evidenceJson,
                String classifierVersion,
                String source
        ) {
            this.scanId = scanId;
            this.observedIp = observedIp;
            this.macAddress = macAddress;
            this.nodeRole = nodeRole;
            this.confidence = confidence;
            this.score = score;
            this.evidenceJson = evidenceJson;
            this.classifierVersion = classifierVersion;
            this.source = source;
        }
    }

    // ========================================
    // BLOCK 23 — NORMALIZE OUI TOKEN
    // ========================================
    private String normalizeOuiToken(String input) {
        if (input == null) {
            return null;
        }

        String hex = input.toUpperCase().replaceAll("[^0-9A-F]", "");
        if (hex.length() < 6) {
            return null;
        }
        hex = hex.substring(0, 6);
        return hex.substring(0, 2) + ":" + hex.substring(2, 4) + ":" + hex.substring(4, 6);
    }

    // ========================================
    // BLOCK 24 — UPSERT OUI METADATA
    // ========================================
    public void upsertOuiMetadata(
            String oui,
            boolean criticalInfrastructure,
            String equipmentType,
            String roleHint,
            String notes
    ) throws Exception {
        String normalizedOui = normalizeOuiToken(oui);
        if (normalizedOui == null) {
            throw new IllegalArgumentException("Invalid OUI: " + oui);
        }

        String sql = """
            INSERT INTO mac_oui_metadata
                (oui, critical_infrastructure, equipment_type, role_hint, notes, updated_at)
            VALUES
                (?, ?, ?, ?, ?, NOW())
            ON CONFLICT (oui)
            DO UPDATE SET
                critical_infrastructure = EXCLUDED.critical_infrastructure,
                equipment_type = EXCLUDED.equipment_type,
                role_hint = EXCLUDED.role_hint,
                notes = EXCLUDED.notes,
                updated_at = NOW()
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            ensureOuiMetadataTable(conn);
            stmt.setString(1, normalizedOui);
            stmt.setBoolean(2, criticalInfrastructure);
            stmt.setString(3, equipmentType);
            stmt.setString(4, roleHint);
            stmt.setString(5, notes);
            stmt.executeUpdate();
        }
    }

    // ========================================
    // BLOCK 25 — GET OUI METADATA
    // ========================================
    public OuiMetadataRecord getOuiMetadata(String oui) throws Exception {
        String normalizedOui = normalizeOuiToken(oui);
        if (normalizedOui == null) {
            return null;
        }

        String sql = """
            SELECT
                m.oui,
                COALESCE(v.vendor_clean, v.vendor, 'Unknown') AS vendor,
                m.critical_infrastructure,
                m.equipment_type,
                m.role_hint,
                m.notes
            FROM mac_oui_metadata m
            LEFT JOIN mac_oui_lookup v
              ON LEFT(REGEXP_REPLACE(UPPER(m.oui), '[^0-9A-F]', '', 'g'), 6)
               = LEFT(REGEXP_REPLACE(UPPER(v.oui), '[^0-9A-F]', '', 'g'), 6)
            WHERE m.oui = ?
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            ensureOuiMetadataTable(conn);
            stmt.setString(1, normalizedOui);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return new OuiMetadataRecord(
                            rs.getString("oui"),
                            rs.getString("vendor"),
                            rs.getBoolean("critical_infrastructure"),
                            rs.getString("equipment_type"),
                            rs.getString("role_hint"),
                            rs.getString("notes")
                    );
                }
            }
        }

        return null;
    }

    // ========================================
    // BLOCK 26 — MAC CRITICAL INFRA LOOKUP
    // ========================================
    public boolean isMacMarkedCriticalInfrastructure(String mac) throws Exception {
        String normalizedOui = normalizeOuiToken(mac);
        if (normalizedOui == null) {
            return false;
        }

        String sql = """
            SELECT critical_infrastructure
            FROM mac_oui_metadata
            WHERE oui = ?
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            ensureOuiMetadataTable(conn);
            stmt.setString(1, normalizedOui);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getBoolean("critical_infrastructure");
                }
            }
        }

        return false;
    }

    // ========================================
    // BLOCK 27 — OUI DTO
    // ========================================
    public static class OuiMetadataRecord {
        public final String oui;
        public final String vendor;
        public final boolean criticalInfrastructure;
        public final String equipmentType;
        public final String roleHint;
        public final String notes;

        public OuiMetadataRecord(
                String oui,
                String vendor,
                boolean criticalInfrastructure,
                String equipmentType,
                String roleHint,
                String notes
        ) {
            this.oui = oui;
            this.vendor = vendor;
            this.criticalInfrastructure = criticalInfrastructure;
            this.equipmentType = equipmentType;
            this.roleHint = roleHint;
            this.notes = notes;
        }
    }

    // ========================================
    // BLOCK 28 — LOAD TRAFFIC ROLE HINTS
    // ========================================
    public List<TrafficRoleHint> loadTrafficRoleHintsForScan(int scanId) throws Exception {
        String sql = """
            WITH latest_capture AS (
                SELECT id
                FROM tcpdump_captures
                WHERE scan_id = ?
                ORDER BY id DESC
                LIMIT 1
            ),
            node_base AS (
                SELECT
                    host(a.observed_ip) AS observed_ip,
                    MAX(a.mac_address) FILTER (WHERE a.mac_address IS NOT NULL) AS mac_address
                FROM arp_bindings a
                WHERE a.scan_id = ?
                  AND a.observed_ip IS NOT NULL
                GROUP BY host(a.observed_ip)
            ),
            flow AS (
                SELECT
                    host(mo.src_ip) AS src_ip,
                    host(mo.dst_ip) AS dst_ip
                FROM mac_observations mo
                JOIN latest_capture lc
                  ON lc.id = mo.capture_id
                WHERE mo.scan_id = ?
                  AND mo.protocol = 'IPv4'
                  AND mo.src_ip IS NOT NULL
                  AND mo.dst_ip IS NOT NULL
            ),
            out_stats AS (
                SELECT
                    src_ip AS observed_ip,
                    COUNT(*) AS outbound_frames,
                    COUNT(DISTINCT dst_ip) AS distinct_outbound_peers
                FROM flow
                GROUP BY src_ip
            ),
            in_stats AS (
                SELECT
                    dst_ip AS observed_ip,
                    COUNT(*) AS inbound_frames,
                    COUNT(DISTINCT src_ip) AS distinct_inbound_peers
                FROM flow
                GROUP BY dst_ip
            ),
            svc AS (
                SELECT
                    host(observed_ip) AS observed_ip,
                    COUNT(*) FILTER (WHERE state = 'open') AS open_service_count
                FROM service_observations
                WHERE scan_id = ?
                GROUP BY host(observed_ip)
            )
            SELECT
                nb.observed_ip,
                nb.mac_address,
                COALESCE(o.outbound_frames, 0) AS outbound_frames,
                COALESCE(i.inbound_frames, 0) AS inbound_frames,
                COALESCE(o.distinct_outbound_peers, 0) AS distinct_outbound_peers,
                COALESCE(i.distinct_inbound_peers, 0) AS distinct_inbound_peers,
                COALESCE(s.open_service_count, 0) AS open_service_count
            FROM node_base nb
            LEFT JOIN out_stats o ON o.observed_ip = nb.observed_ip
            LEFT JOIN in_stats i ON i.observed_ip = nb.observed_ip
            LEFT JOIN svc s ON s.observed_ip = nb.observed_ip
            ORDER BY nb.observed_ip
        """;

        List<TrafficRoleHint> rows = new ArrayList<>();

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            stmt.setInt(1, scanId);
            stmt.setInt(2, scanId);
            stmt.setInt(3, scanId);
            stmt.setInt(4, scanId);

            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    rows.add(new TrafficRoleHint(
                            rs.getString("observed_ip"),
                            rs.getString("mac_address"),
                            rs.getInt("outbound_frames"),
                            rs.getInt("inbound_frames"),
                            rs.getInt("distinct_outbound_peers"),
                            rs.getInt("distinct_inbound_peers"),
                            rs.getInt("open_service_count")
                    ));
                }
            }
        }

        return rows;
    }

    // ========================================
    // BLOCK 29 — TRAFFIC ROLE HINT DTO
    // ========================================
    public static class TrafficRoleHint {
        public final String observedIp;
        public final String macAddress;
        public final int outboundFrames;
        public final int inboundFrames;
        public final int distinctOutboundPeers;
        public final int distinctInboundPeers;
        public final int openServiceCount;

        public TrafficRoleHint(
                String observedIp,
                String macAddress,
                int outboundFrames,
                int inboundFrames,
                int distinctOutboundPeers,
                int distinctInboundPeers,
                int openServiceCount
        ) {
            this.observedIp = observedIp;
            this.macAddress = macAddress;
            this.outboundFrames = outboundFrames;
            this.inboundFrames = inboundFrames;
            this.distinctOutboundPeers = distinctOutboundPeers;
            this.distinctInboundPeers = distinctInboundPeers;
            this.openServiceCount = openServiceCount;
        }
    }

    // ========================================
    // BLOCK 30 — CREATE SNMP WALK RUN
    // ========================================
    public long createSnmpWalkRun(Integer scanId, String observedIp, String authMode, String oidRoot) throws Exception {
        ensureSnmpWalkSchema();

        String sql = """
            INSERT INTO snmp_walk_runs
                (scan_id, observed_ip, auth_mode, oid_root, status)
            VALUES
                (?, ?::inet, ?, ?, 'running')
            RETURNING id
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            if (scanId != null) {
                stmt.setInt(1, scanId);
            } else {
                stmt.setNull(1, Types.INTEGER);
            }
            stmt.setString(2, observedIp);
            stmt.setString(3, authMode != null ? authMode : "v2c");
            stmt.setString(4, oidRoot != null ? oidRoot : "1.3.6.1.2.1");

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getLong("id");
                }
            }
        }

        throw new RuntimeException("Failed to create snmp_walk_runs record.");
    }

    // ========================================
    // BLOCK 31 — COMPLETE SNMP WALK RUN
    // ========================================
    public void completeSnmpWalkRun(long runId, String rawOutput) throws Exception {
        String sql = """
            UPDATE snmp_walk_runs
            SET status = 'complete',
                raw_output = ?,
                error_text = NULL,
                completed_at = now()
            WHERE id = ?
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            stmt.setString(1, rawOutput);
            stmt.setLong(2, runId);
            stmt.executeUpdate();
        }
    }

    // ========================================
    // BLOCK 32 — FAIL SNMP WALK RUN
    // ========================================
    public void failSnmpWalkRun(long runId, String errorText, String rawOutput) throws Exception {
        String sql = """
            UPDATE snmp_walk_runs
            SET status = 'failed',
                error_text = ?,
                raw_output = ?,
                completed_at = now()
            WHERE id = ?
        """;

        try (
                Connection conn = getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)
        ) {
            stmt.setString(1, errorText);
            stmt.setString(2, rawOutput);
            stmt.setLong(3, runId);
            stmt.executeUpdate();
        }
    }
}
