--
-- PostgreSQL database dump
--

\restrict HF8CcI1zS0MHfmofzrFIOwN9pHuEA4XWIawHRLfLhLVDPZC6exiMjBUg7KhY9Nh

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

-- Started on 2026-04-22 10:57:22 PDT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3660 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 17073)
-- Name: arp_bindings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.arp_bindings (
    id bigint NOT NULL,
    scan_id integer NOT NULL,
    observed_ip inet NOT NULL,
    mac_address character varying(17),
    source text NOT NULL,
    rtt_ms double precision,
    response_type text,
    first_seen timestamp with time zone DEFAULT now() NOT NULL,
    last_seen timestamp with time zone DEFAULT now() NOT NULL,
    seen_count integer DEFAULT 1 NOT NULL,
    CONSTRAINT chk_arp_mac_format CHECK (((mac_address)::text ~ '^[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){5}$'::text))
);


ALTER TABLE public.arp_bindings OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 17072)
-- Name: arp_bindings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.arp_bindings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arp_bindings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 17159)
-- Name: inferred_devices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inferred_devices (
    id bigint NOT NULL,
    scan_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.inferred_devices OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 17158)
-- Name: inferred_devices_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inferred_devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inferred_devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 17241)
-- Name: mac_observations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mac_observations (
    id bigint NOT NULL,
    scan_id integer NOT NULL,
    capture_id bigint NOT NULL,
    observed_at timestamp with time zone DEFAULT now() NOT NULL,
    src_mac text,
    src_ip inet,
    dst_mac text,
    dst_ip inet,
    protocol text DEFAULT 'ARP'::text NOT NULL,
    note text,
    raw_line text
);


ALTER TABLE public.mac_observations OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 17240)
-- Name: mac_observations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.mac_observations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.mac_observations_id_seq OWNER TO postgres;

--
-- TOC entry 3661 (class 0 OID 0)
-- Dependencies: 235
-- Name: mac_observations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.mac_observations_id_seq OWNED BY public.mac_observations.id;


--
-- TOC entry 219 (class 1259 OID 17097)
-- Name: mac_oui_lookup; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mac_oui_lookup (
    oui character varying(8) NOT NULL,
    vendor text NOT NULL,
    vendor_clean text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    is_virtual boolean DEFAULT false NOT NULL,
    CONSTRAINT chk_oui_format CHECK (((oui)::text ~ '^[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){2}$'::text))
);


ALTER TABLE public.mac_oui_lookup OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 17459)
-- Name: mac_oui_metadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mac_oui_metadata (
    oui character varying(8) NOT NULL,
    critical_infrastructure boolean DEFAULT false NOT NULL,
    equipment_type text,
    role_hint text,
    notes text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.mac_oui_metadata OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17133)
-- Name: mac_peer_stats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mac_peer_stats (
    id bigint NOT NULL,
    scan_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.mac_peer_stats OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 17132)
-- Name: mac_peer_stats_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mac_peer_stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mac_peer_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 17120)
-- Name: mac_relationships; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mac_relationships (
    id bigint NOT NULL,
    scan_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.mac_relationships OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 17119)
-- Name: mac_relationships_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mac_relationships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mac_relationships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 17107)
-- Name: network_edges; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.network_edges (
    id bigint NOT NULL,
    scan_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.network_edges OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 17106)
-- Name: network_edges_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.network_edges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.network_edges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 17420)
-- Name: node_classifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.node_classifications (
    id bigint NOT NULL,
    scan_id integer NOT NULL,
    observed_ip inet NOT NULL,
    mac_address character varying(17),
    node_role text NOT NULL,
    confidence text NOT NULL,
    score numeric(6,3),
    evidence_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    classifier_version text DEFAULT 'v1'::text NOT NULL,
    source text DEFAULT 'rule_engine'::text NOT NULL,
    classified_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT node_classifications_confidence_check CHECK ((confidence = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])))
);


ALTER TABLE public.node_classifications OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 17419)
-- Name: node_classifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.node_classifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.node_classifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 17172)
-- Name: nodes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nodes (
    id bigint NOT NULL,
    scan_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.nodes OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 17171)
-- Name: nodes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.nodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 17058)
-- Name: scan_runs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.scan_runs (
    id integer NOT NULL,
    subnet text NOT NULL,
    interface text DEFAULT 'auto'::text NOT NULL,
    target_host text DEFAULT 'local'::text NOT NULL,
    ssh_used boolean DEFAULT false NOT NULL,
    status text DEFAULT 'running'::text NOT NULL,
    raw_output text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT scan_runs_status_check CHECK ((status = ANY (ARRAY['running'::text, 'complete'::text, 'failed'::text])))
);


ALTER TABLE public.scan_runs OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 17057)
-- Name: scan_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.scan_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scan_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 17395)
-- Name: service_observations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_observations (
    id bigint NOT NULL,
    scan_id integer NOT NULL,
    observed_ip inet NOT NULL,
    mac_address character varying(17),
    transport text DEFAULT 'tcp'::text NOT NULL,
    port integer NOT NULL,
    state text DEFAULT 'open'::text NOT NULL,
    service_name text,
    product text,
    version text,
    extra_info text,
    source text DEFAULT 'nmap_sV'::text NOT NULL,
    observed_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT service_observations_port_check CHECK (((port >= 1) AND (port <= 65535))),
    CONSTRAINT service_observations_transport_check CHECK ((transport = ANY (ARRAY['tcp'::text, 'udp'::text])))
);


ALTER TABLE public.service_observations OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 17394)
-- Name: service_observations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service_observations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_observations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 17470)
-- Name: snmp_walk_runs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.snmp_walk_runs (
    id bigint NOT NULL,
    scan_id integer,
    observed_ip inet NOT NULL,
    auth_mode text DEFAULT 'v2c'::text NOT NULL,
    oid_root text DEFAULT '1.3.6.1.2.1'::text NOT NULL,
    status text DEFAULT 'running'::text NOT NULL,
    raw_output text,
    error_text text,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone
);


ALTER TABLE public.snmp_walk_runs OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 17469)
-- Name: snmp_walk_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.snmp_walk_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.snmp_walk_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 17221)
-- Name: tcpdump_captures; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tcpdump_captures (
    id bigint NOT NULL,
    scan_id integer NOT NULL,
    capture_method text NOT NULL,
    capture_host text NOT NULL,
    interface_name text NOT NULL,
    capture_filter text DEFAULT 'arp'::text NOT NULL,
    duration_seconds integer DEFAULT 20 NOT NULL,
    status text DEFAULT 'running'::text NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    ended_at timestamp with time zone,
    raw_output text,
    CONSTRAINT tcpdump_captures_capture_method_check CHECK ((capture_method = ANY (ARRAY['local'::text, 'ssh'::text])))
);


ALTER TABLE public.tcpdump_captures OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 17220)
-- Name: tcpdump_captures_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tcpdump_captures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tcpdump_captures_id_seq OWNER TO postgres;

--
-- TOC entry 3662 (class 0 OID 0)
-- Dependencies: 233
-- Name: tcpdump_captures_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tcpdump_captures_id_seq OWNED BY public.tcpdump_captures.id;


--
-- TOC entry 242 (class 1259 OID 17301)
-- Name: vw_duplicate_ip_claims; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_duplicate_ip_claims AS
 SELECT m.scan_id,
    m.capture_id,
    m.observed_at,
    m.src_ip AS suspected_ip,
    m.src_mac,
    COALESCE(v.vendor_clean, v.vendor, 'Unknown'::text) AS src_vendor,
    m.dst_mac,
    m.raw_line
   FROM (public.mac_observations m
     LEFT JOIN public.mac_oui_lookup v ON (("left"(regexp_replace(upper(m.src_mac), '[^0-9A-F]'::text, ''::text, 'g'::text), 6) = "left"(regexp_replace(upper((v.oui)::text), '[^0-9A-F]'::text, ''::text, 'g'::text), 6))))
  WHERE ((m.protocol = 'ARP'::text) AND (m.note = 'is-at'::text) AND (m.src_ip IS NOT NULL) AND (m.src_mac IS NOT NULL));


ALTER VIEW public.vw_duplicate_ip_claims OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 17296)
-- Name: vw_duplicate_ip_suspects; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_duplicate_ip_suspects AS
 SELECT m.scan_id,
    m.capture_id,
    m.src_ip AS suspected_ip,
    count(*) AS arp_reply_count,
    count(DISTINCT m.src_mac) AS distinct_mac_count,
    string_agg(DISTINCT m.src_mac, ', '::text) AS mac_list,
    string_agg(DISTINCT COALESCE(v.vendor_clean, v.vendor, 'Unknown'::text), ', '::text) AS vendor_list,
    min(m.observed_at) AS first_seen,
    max(m.observed_at) AS last_seen
   FROM (public.mac_observations m
     LEFT JOIN public.mac_oui_lookup v ON (("left"(regexp_replace(upper(m.src_mac), '[^0-9A-F]'::text, ''::text, 'g'::text), 6) = "left"(regexp_replace(upper((v.oui)::text), '[^0-9A-F]'::text, ''::text, 'g'::text), 6))))
  WHERE ((m.protocol = 'ARP'::text) AND (m.note = 'is-at'::text) AND (m.src_ip IS NOT NULL) AND (m.src_mac IS NOT NULL))
  GROUP BY m.scan_id, m.capture_id, m.src_ip
 HAVING (count(DISTINCT m.src_mac) > 1);


ALTER VIEW public.vw_duplicate_ip_suspects OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 17443)
-- Name: vw_likely_file_sharing_nodes; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_likely_file_sharing_nodes AS
 WITH svc AS (
         SELECT so.scan_id,
            so.observed_ip,
            so.mac_address,
            max(
                CASE
                    WHEN (so.port = 445) THEN 1
                    ELSE 0
                END) AS has_445,
            max(
                CASE
                    WHEN (so.port = 139) THEN 1
                    ELSE 0
                END) AS has_139,
            max(
                CASE
                    WHEN (so.port = 137) THEN 1
                    ELSE 0
                END) AS has_137,
            max(
                CASE
                    WHEN (so.port = 138) THEN 1
                    ELSE 0
                END) AS has_138,
            string_agg(DISTINCT COALESCE(so.service_name, '?'::text), ', '::text ORDER BY COALESCE(so.service_name, '?'::text)) AS services
           FROM public.service_observations so
          WHERE (so.state = 'open'::text)
          GROUP BY so.scan_id, so.observed_ip, so.mac_address
        ), base AS (
         SELECT a.scan_id,
            a.observed_ip,
            a.mac_address,
            COALESCE(v.vendor_clean, v.vendor, 'Unknown'::text) AS vendor
           FROM (public.arp_bindings a
             LEFT JOIN public.mac_oui_lookup v ON (("left"(regexp_replace(upper((a.mac_address)::text), '[^0-9A-F]'::text, ''::text, 'g'::text), 6) = "left"(regexp_replace(upper((v.oui)::text), '[^0-9A-F]'::text, ''::text, 'g'::text), 6))))
        )
 SELECT COALESCE(s.scan_id, b.scan_id) AS scan_id,
    COALESCE(s.observed_ip, b.observed_ip) AS observed_ip,
    COALESCE(s.mac_address, b.mac_address) AS mac_address,
    b.vendor,
    COALESCE(s.services, ''::text) AS services,
    COALESCE(s.has_445, 0) AS has_445,
    COALESCE(s.has_139, 0) AS has_139,
    COALESCE(s.has_137, 0) AS has_137,
    COALESCE(s.has_138, 0) AS has_138,
        CASE
            WHEN ((COALESCE(s.has_445, 0) = 1) AND ((COALESCE(s.has_139, 0) = 1) OR (COALESCE(s.has_137, 0) = 1))) THEN 'Likely Windows/File Server (high)'::text
            WHEN (COALESCE(s.has_445, 0) = 1) THEN 'Likely SMB File Sharing (medium)'::text
            WHEN (COALESCE(s.has_139, 0) = 1) THEN 'Likely NetBIOS/Legacy File Sharing (medium)'::text
            ELSE 'Weak/No SMB Signal'::text
        END AS file_share_assessment
   FROM (svc s
     FULL JOIN base b ON (((b.scan_id = s.scan_id) AND (b.observed_ip = s.observed_ip) AND (NOT ((b.mac_address)::text IS DISTINCT FROM (s.mac_address)::text)))));


ALTER VIEW public.vw_likely_file_sharing_nodes OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 17277)
-- Name: vw_mac_observations_enriched; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_mac_observations_enriched AS
 SELECT m.id,
    m.scan_id,
    m.capture_id,
    m.observed_at,
    m.protocol,
    m.note,
    m.src_mac,
    m.src_ip,
    m.dst_mac,
    m.dst_ip,
    m.raw_line,
    COALESCE(vs.vendor_clean, vs.vendor, 'Unknown'::text) AS src_vendor,
    COALESCE(vd.vendor_clean, vd.vendor, 'Unknown'::text) AS dst_vendor,
        CASE
            WHEN (upper(m.dst_mac) = 'FF:FF:FF:FF:FF:FF'::text) THEN true
            ELSE false
        END AS is_broadcast,
        CASE
            WHEN (upper(replace(m.dst_mac, '-'::text, ':'::text)) ~~ '33:33:%'::text) THEN true
            ELSE false
        END AS is_ipv6_multicast,
        CASE
            WHEN (upper(replace(m.dst_mac, '-'::text, ':'::text)) ~~ '01:00:5E:%'::text) THEN true
            ELSE false
        END AS is_ipv4_multicast
   FROM ((public.mac_observations m
     LEFT JOIN public.mac_oui_lookup vs ON (("left"(regexp_replace(upper(m.src_mac), '[^0-9A-F]'::text, ''::text, 'g'::text), 6) = "left"(regexp_replace(upper((vs.oui)::text), '[^0-9A-F]'::text, ''::text, 'g'::text), 6))))
     LEFT JOIN public.mac_oui_lookup vd ON (("left"(regexp_replace(upper(m.dst_mac), '[^0-9A-F]'::text, ''::text, 'g'::text), 6) = "left"(regexp_replace(upper((vd.oui)::text), '[^0-9A-F]'::text, ''::text, 'g'::text), 6))));


ALTER VIEW public.vw_mac_observations_enriched OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 17282)
-- Name: vw_network_noise_detail; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_network_noise_detail AS
 SELECT m.id,
    m.scan_id,
    m.capture_id,
    m.observed_at,
    m.protocol,
    m.note,
    m.src_mac,
    m.src_ip,
    m.dst_mac,
    m.dst_ip,
    m.raw_line,
    COALESCE(vs.vendor_clean, vs.vendor, 'Unknown'::text) AS src_vendor,
    COALESCE(vd.vendor_clean, vd.vendor, 'Unknown'::text) AS dst_vendor,
        CASE
            WHEN (upper(COALESCE(m.dst_mac, ''::text)) = 'FF:FF:FF:FF:FF:FF'::text) THEN true
            ELSE false
        END AS is_broadcast,
        CASE
            WHEN (upper(replace(COALESCE(m.dst_mac, ''::text), '-'::text, ':'::text)) ~~ '33:33:%'::text) THEN true
            ELSE false
        END AS is_ipv6_multicast,
        CASE
            WHEN (upper(replace(COALESCE(m.dst_mac, ''::text), '-'::text, ':'::text)) ~~ '01:00:5E:%'::text) THEN true
            ELSE false
        END AS is_ipv4_multicast,
        CASE
            WHEN (m.protocol = 'ARP'::text) THEN 'ARP'::text
            WHEN (upper(COALESCE(m.dst_mac, ''::text)) = 'FF:FF:FF:FF:FF:FF'::text) THEN 'Broadcast'::text
            WHEN (upper(replace(COALESCE(m.dst_mac, ''::text), '-'::text, ':'::text)) ~~ '33:33:%'::text) THEN 'IPv6 Multicast'::text
            WHEN (upper(replace(COALESCE(m.dst_mac, ''::text), '-'::text, ':'::text)) ~~ '01:00:5E:%'::text) THEN 'IPv4 Multicast'::text
            WHEN (m.protocol = 'IPv4'::text) THEN 'IPv4 Unicast'::text
            WHEN (m.protocol = 'IPv6'::text) THEN 'IPv6 Unicast/Other'::text
            ELSE 'Generic Ethernet'::text
        END AS traffic_class,
        CASE
            WHEN (m.protocol = 'ARP'::text) THEN true
            WHEN (upper(COALESCE(m.dst_mac, ''::text)) = 'FF:FF:FF:FF:FF:FF'::text) THEN true
            WHEN (upper(replace(COALESCE(m.dst_mac, ''::text), '-'::text, ':'::text)) ~~ '33:33:%'::text) THEN true
            WHEN (upper(replace(COALESCE(m.dst_mac, ''::text), '-'::text, ':'::text)) ~~ '01:00:5E:%'::text) THEN true
            ELSE false
        END AS is_noise_like
   FROM ((public.mac_observations m
     LEFT JOIN public.mac_oui_lookup vs ON (("left"(regexp_replace(upper(m.src_mac), '[^0-9A-F]'::text, ''::text, 'g'::text), 6) = "left"(regexp_replace(upper((vs.oui)::text), '[^0-9A-F]'::text, ''::text, 'g'::text), 6))))
     LEFT JOIN public.mac_oui_lookup vd ON (("left"(regexp_replace(upper(m.dst_mac), '[^0-9A-F]'::text, ''::text, 'g'::text), 6) = "left"(regexp_replace(upper((vd.oui)::text), '[^0-9A-F]'::text, ''::text, 'g'::text), 6))));


ALTER VIEW public.vw_network_noise_detail OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 17287)
-- Name: vw_network_noise_summary; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_network_noise_summary AS
 SELECT scan_id,
    capture_id,
    traffic_class,
    count(*) AS row_count,
    round(((100.0 * (count(*))::numeric) / NULLIF(sum(count(*)) OVER (PARTITION BY scan_id, capture_id), (0)::numeric)), 2) AS pct_of_capture
   FROM public.vw_network_noise_detail
  GROUP BY scan_id, capture_id, traffic_class;


ALTER VIEW public.vw_network_noise_summary OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 17292)
-- Name: vw_network_top_talkers; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_network_top_talkers AS
 SELECT scan_id,
    capture_id,
    src_mac,
    src_vendor,
    count(*) AS frame_count
   FROM public.vw_network_noise_detail
  GROUP BY scan_id, capture_id, src_mac, src_vendor;


ALTER VIEW public.vw_network_top_talkers OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17211)
-- Name: vw_rtt_cluster_nodes; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_rtt_cluster_nodes AS
 SELECT a.scan_id,
    (round(((a.rtt_ms * (2)::double precision))::numeric, 0) / 2.0) AS rtt_bucket,
    a.observed_ip,
    a.mac_address,
    COALESCE(v.vendor_clean, v.vendor, 'Unknown'::text) AS resolved_vendor,
    a.rtt_ms,
    a.response_type,
    a.source,
    a.seen_count,
    a.last_seen
   FROM (public.arp_bindings a
     LEFT JOIN public.mac_oui_lookup v ON (("left"(regexp_replace(upper((a.mac_address)::text), '[^0-9A-F]'::text, ''::text, 'g'::text), 6) = "left"(regexp_replace(upper((v.oui)::text), '[^0-9A-F]'::text, ''::text, 'g'::text), 6))))
  WHERE (a.rtt_ms IS NOT NULL);


ALTER VIEW public.vw_rtt_cluster_nodes OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 17216)
-- Name: vw_rtt_cluster_summary; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_rtt_cluster_summary AS
 SELECT scan_id,
    (round(((rtt_ms * (2)::double precision))::numeric, 0) / 2.0) AS rtt_bucket,
    count(*) AS node_count,
    min(rtt_ms) AS min_rtt,
    max(rtt_ms) AS max_rtt,
    avg(rtt_ms) AS avg_rtt
   FROM public.arp_bindings
  WHERE (rtt_ms IS NOT NULL)
  GROUP BY scan_id, (round(((rtt_ms * (2)::double precision))::numeric, 0) / 2.0);


ALTER VIEW public.vw_rtt_cluster_summary OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 17196)
-- Name: vw_scan_nodes; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_scan_nodes AS
 SELECT a.id,
    a.scan_id,
    a.observed_ip,
    a.mac_address,
    a.source,
    a.rtt_ms,
    a.response_type,
    a.first_seen,
    a.last_seen,
    a.seen_count,
    v.oui,
    v.vendor,
    v.vendor_clean,
    v.is_virtual,
    COALESCE(v.vendor_clean, v.vendor, 'Unknown'::text) AS resolved_vendor
   FROM (public.arp_bindings a
     LEFT JOIN public.mac_oui_lookup v ON (("left"(regexp_replace(upper((a.mac_address)::text), '[^0-9A-F]'::text, ''::text, 'g'::text), 6) = "left"(regexp_replace(upper((v.oui)::text), '[^0-9A-F]'::text, ''::text, 'g'::text), 6))));


ALTER VIEW public.vw_scan_nodes OWNER TO postgres;

--
-- TOC entry 3406 (class 2604 OID 17244)
-- Name: mac_observations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mac_observations ALTER COLUMN id SET DEFAULT nextval('public.mac_observations_id_seq'::regclass);


--
-- TOC entry 3401 (class 2604 OID 17224)
-- Name: tcpdump_captures id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tcpdump_captures ALTER COLUMN id SET DEFAULT nextval('public.tcpdump_captures_id_seq'::regclass);


--
-- TOC entry 3434 (class 2606 OID 17083)
-- Name: arp_bindings arp_bindings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.arp_bindings
    ADD CONSTRAINT arp_bindings_pkey PRIMARY KEY (id);


--
-- TOC entry 3456 (class 2606 OID 17164)
-- Name: inferred_devices inferred_devices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inferred_devices
    ADD CONSTRAINT inferred_devices_pkey PRIMARY KEY (id);


--
-- TOC entry 3466 (class 2606 OID 17250)
-- Name: mac_observations mac_observations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mac_observations
    ADD CONSTRAINT mac_observations_pkey PRIMARY KEY (id);


--
-- TOC entry 3444 (class 2606 OID 17105)
-- Name: mac_oui_lookup mac_oui_lookup_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mac_oui_lookup
    ADD CONSTRAINT mac_oui_lookup_pkey PRIMARY KEY (oui);


--
-- TOC entry 3485 (class 2606 OID 17467)
-- Name: mac_oui_metadata mac_oui_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mac_oui_metadata
    ADD CONSTRAINT mac_oui_metadata_pkey PRIMARY KEY (oui);


--
-- TOC entry 3453 (class 2606 OID 17138)
-- Name: mac_peer_stats mac_peer_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mac_peer_stats
    ADD CONSTRAINT mac_peer_stats_pkey PRIMARY KEY (id);


--
-- TOC entry 3450 (class 2606 OID 17125)
-- Name: mac_relationships mac_relationships_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mac_relationships
    ADD CONSTRAINT mac_relationships_pkey PRIMARY KEY (id);


--
-- TOC entry 3447 (class 2606 OID 17112)
-- Name: network_edges network_edges_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.network_edges
    ADD CONSTRAINT network_edges_pkey PRIMARY KEY (id);


--
-- TOC entry 3480 (class 2606 OID 17431)
-- Name: node_classifications node_classifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.node_classifications
    ADD CONSTRAINT node_classifications_pkey PRIMARY KEY (id);


--
-- TOC entry 3459 (class 2606 OID 17177)
-- Name: nodes nodes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nodes
    ADD CONSTRAINT nodes_pkey PRIMARY KEY (id);


--
-- TOC entry 3432 (class 2606 OID 17070)
-- Name: scan_runs scan_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scan_runs
    ADD CONSTRAINT scan_runs_pkey PRIMARY KEY (id);


--
-- TOC entry 3472 (class 2606 OID 17407)
-- Name: service_observations service_observations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_observations
    ADD CONSTRAINT service_observations_pkey PRIMARY KEY (id);


--
-- TOC entry 3489 (class 2606 OID 17480)
-- Name: snmp_walk_runs snmp_walk_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.snmp_walk_runs
    ADD CONSTRAINT snmp_walk_runs_pkey PRIMARY KEY (id);


--
-- TOC entry 3462 (class 2606 OID 17233)
-- Name: tcpdump_captures tcpdump_captures_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tcpdump_captures
    ADD CONSTRAINT tcpdump_captures_pkey PRIMARY KEY (id);


--
-- TOC entry 3442 (class 2606 OID 17393)
-- Name: arp_bindings uq_arp_bindings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.arp_bindings
    ADD CONSTRAINT uq_arp_bindings UNIQUE NULLS NOT DISTINCT (scan_id, observed_ip, mac_address, source);


--
-- TOC entry 3482 (class 2606 OID 17433)
-- Name: node_classifications uq_node_classifications; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.node_classifications
    ADD CONSTRAINT uq_node_classifications UNIQUE NULLS NOT DISTINCT (scan_id, observed_ip, mac_address, node_role, classifier_version);


--
-- TOC entry 3474 (class 2606 OID 17409)
-- Name: service_observations uq_service_observations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_observations
    ADD CONSTRAINT uq_service_observations UNIQUE NULLS NOT DISTINCT (scan_id, observed_ip, mac_address, transport, port, source);


--
-- TOC entry 3435 (class 1259 OID 17096)
-- Name: idx_arp_bindings_mac_oui_expr; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_arp_bindings_mac_oui_expr ON public.arp_bindings USING btree ("substring"((mac_address)::text, 1, 8));


--
-- TOC entry 3436 (class 1259 OID 17091)
-- Name: idx_arp_bindings_scan_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_arp_bindings_scan_id ON public.arp_bindings USING btree (scan_id);


--
-- TOC entry 3437 (class 1259 OID 17092)
-- Name: idx_arp_bindings_scan_ip; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_arp_bindings_scan_ip ON public.arp_bindings USING btree (scan_id, observed_ip);


--
-- TOC entry 3438 (class 1259 OID 17093)
-- Name: idx_arp_bindings_scan_mac; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_arp_bindings_scan_mac ON public.arp_bindings USING btree (scan_id, mac_address);


--
-- TOC entry 3439 (class 1259 OID 17095)
-- Name: idx_arp_bindings_scan_response_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_arp_bindings_scan_response_type ON public.arp_bindings USING btree (scan_id, response_type);


--
-- TOC entry 3440 (class 1259 OID 17094)
-- Name: idx_arp_bindings_scan_rtt; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_arp_bindings_scan_rtt ON public.arp_bindings USING btree (scan_id, rtt_ms);


--
-- TOC entry 3454 (class 1259 OID 17170)
-- Name: idx_inferred_devices_scan_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_inferred_devices_scan_id ON public.inferred_devices USING btree (scan_id);


--
-- TOC entry 3463 (class 1259 OID 17264)
-- Name: idx_mac_observations_capture_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_mac_observations_capture_id ON public.mac_observations USING btree (capture_id);


--
-- TOC entry 3464 (class 1259 OID 17263)
-- Name: idx_mac_observations_scan_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_mac_observations_scan_id ON public.mac_observations USING btree (scan_id);


--
-- TOC entry 3451 (class 1259 OID 17144)
-- Name: idx_mac_peer_stats_scan_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_mac_peer_stats_scan_id ON public.mac_peer_stats USING btree (scan_id);


--
-- TOC entry 3448 (class 1259 OID 17131)
-- Name: idx_mac_relationships_scan_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_mac_relationships_scan_id ON public.mac_relationships USING btree (scan_id);


--
-- TOC entry 3445 (class 1259 OID 17118)
-- Name: idx_network_edges_scan_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_network_edges_scan_id ON public.network_edges USING btree (scan_id);


--
-- TOC entry 3475 (class 1259 OID 17442)
-- Name: idx_node_class_evidence_gin; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_node_class_evidence_gin ON public.node_classifications USING gin (evidence_json);


--
-- TOC entry 3476 (class 1259 OID 17441)
-- Name: idx_node_class_scan_conf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_node_class_scan_conf ON public.node_classifications USING btree (scan_id, confidence);


--
-- TOC entry 3477 (class 1259 OID 17439)
-- Name: idx_node_class_scan_ip; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_node_class_scan_ip ON public.node_classifications USING btree (scan_id, observed_ip);


--
-- TOC entry 3478 (class 1259 OID 17440)
-- Name: idx_node_class_scan_role; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_node_class_scan_role ON public.node_classifications USING btree (scan_id, node_role);


--
-- TOC entry 3457 (class 1259 OID 17183)
-- Name: idx_nodes_scan_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_nodes_scan_id ON public.nodes USING btree (scan_id);


--
-- TOC entry 3483 (class 1259 OID 17468)
-- Name: idx_oui_metadata_critical; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_oui_metadata_critical ON public.mac_oui_metadata USING btree (critical_infrastructure);


--
-- TOC entry 3430 (class 1259 OID 17071)
-- Name: idx_scan_runs_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_scan_runs_created_at ON public.scan_runs USING btree (created_at DESC);


--
-- TOC entry 3467 (class 1259 OID 17415)
-- Name: idx_service_obs_scan_ip; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_service_obs_scan_ip ON public.service_observations USING btree (scan_id, observed_ip);


--
-- TOC entry 3468 (class 1259 OID 17418)
-- Name: idx_service_obs_scan_mac; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_service_obs_scan_mac ON public.service_observations USING btree (scan_id, mac_address);


--
-- TOC entry 3469 (class 1259 OID 17416)
-- Name: idx_service_obs_scan_port; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_service_obs_scan_port ON public.service_observations USING btree (scan_id, port);


--
-- TOC entry 3470 (class 1259 OID 17417)
-- Name: idx_service_obs_scan_service; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_service_obs_scan_service ON public.service_observations USING btree (scan_id, service_name);


--
-- TOC entry 3486 (class 1259 OID 17487)
-- Name: idx_snmp_walk_runs_ip; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_snmp_walk_runs_ip ON public.snmp_walk_runs USING btree (observed_ip, id DESC);


--
-- TOC entry 3487 (class 1259 OID 17486)
-- Name: idx_snmp_walk_runs_scan; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_snmp_walk_runs_scan ON public.snmp_walk_runs USING btree (scan_id, id DESC);


--
-- TOC entry 3460 (class 1259 OID 17262)
-- Name: idx_tcpdump_captures_scan_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_tcpdump_captures_scan_id ON public.tcpdump_captures USING btree (scan_id);


--
-- TOC entry 3490 (class 2606 OID 17086)
-- Name: arp_bindings arp_bindings_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.arp_bindings
    ADD CONSTRAINT arp_bindings_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scan_runs(id) ON DELETE CASCADE;


--
-- TOC entry 3494 (class 2606 OID 17165)
-- Name: inferred_devices inferred_devices_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inferred_devices
    ADD CONSTRAINT inferred_devices_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scan_runs(id) ON DELETE CASCADE;


--
-- TOC entry 3497 (class 2606 OID 17256)
-- Name: mac_observations mac_observations_capture_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mac_observations
    ADD CONSTRAINT mac_observations_capture_id_fkey FOREIGN KEY (capture_id) REFERENCES public.tcpdump_captures(id) ON DELETE CASCADE;


--
-- TOC entry 3498 (class 2606 OID 17251)
-- Name: mac_observations mac_observations_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mac_observations
    ADD CONSTRAINT mac_observations_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scan_runs(id) ON DELETE CASCADE;


--
-- TOC entry 3493 (class 2606 OID 17139)
-- Name: mac_peer_stats mac_peer_stats_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mac_peer_stats
    ADD CONSTRAINT mac_peer_stats_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scan_runs(id) ON DELETE CASCADE;


--
-- TOC entry 3492 (class 2606 OID 17126)
-- Name: mac_relationships mac_relationships_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mac_relationships
    ADD CONSTRAINT mac_relationships_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scan_runs(id) ON DELETE CASCADE;


--
-- TOC entry 3491 (class 2606 OID 17113)
-- Name: network_edges network_edges_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.network_edges
    ADD CONSTRAINT network_edges_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scan_runs(id) ON DELETE CASCADE;


--
-- TOC entry 3500 (class 2606 OID 17434)
-- Name: node_classifications node_classifications_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.node_classifications
    ADD CONSTRAINT node_classifications_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scan_runs(id) ON DELETE CASCADE;


--
-- TOC entry 3495 (class 2606 OID 17178)
-- Name: nodes nodes_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nodes
    ADD CONSTRAINT nodes_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scan_runs(id) ON DELETE CASCADE;


--
-- TOC entry 3499 (class 2606 OID 17410)
-- Name: service_observations service_observations_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_observations
    ADD CONSTRAINT service_observations_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scan_runs(id) ON DELETE CASCADE;


--
-- TOC entry 3501 (class 2606 OID 17481)
-- Name: snmp_walk_runs snmp_walk_runs_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.snmp_walk_runs
    ADD CONSTRAINT snmp_walk_runs_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scan_runs(id) ON DELETE CASCADE;


--
-- TOC entry 3496 (class 2606 OID 17234)
-- Name: tcpdump_captures tcpdump_captures_scan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tcpdump_captures
    ADD CONSTRAINT tcpdump_captures_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scan_runs(id) ON DELETE CASCADE;


-- Completed on 2026-04-22 10:57:22 PDT

--
-- PostgreSQL database dump complete
--

\unrestrict HF8CcI1zS0MHfmofzrFIOwN9pHuEA4XWIawHRLfLhLVDPZC6exiMjBUg7KhY9Nh

